# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Inner column type record distance function
#'
#' @param a record a
#' @param b record b
#' @param col_type A vector encoding the column type for each column in the dataset. Can take values
#' in "categorical", "ordinal", "string", or "numeric"
#' @param string_dist String distance function. Default is edit distance. Function must take at least
#' two arguments (strings)
#' @param weights A vector of weights for each column for making some column distances more important. Must sum to 1.
#' Defaults to equal weights.
#' @param orders A named list containing the order of the levels in each ordinal column. Defaults to NULL,
#' which corresponds to no ordinal variables.
#' @export
dist_col_type <- function(a, b, col_type, weights, orders) {
    .Call(`_representr_dist_col_type`, a, b, col_type, weights, orders)
}

#' String distance functions
#'
#' @param str1 string 1
#' @param str2 string 2.
NULL

#'
#' @references {
#'   M. E., Macherki (2016): Algorithm:Levenshtein Rcpp. figshare. Software. https://doi.org/10.6084/m9.figshare.3386308.v1
#' }
#' @export
levenshtein <- function(str1, str2) {
    .Call(`_representr_levenshtein`, str1, str2)
}

